version: "3"
services:
  app:
    image: node:16.14.0
    working_dir: /src
    tty: true
    ports:
      - '3000:3000'
    volumes:
      - ./doc/:/src/app
      - ./server/:/src/srever
    command: >
      bash -c "npm install &&
      npm install nodemon -g &&
      nodemon server/server.js"
